name: Deploy app

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

env:
  VERSION: $(date +%s)

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
    - name: VERSION
      run: echo v${VERSION}
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t alexgavr89/test_deploy:v${VERSION}
      
    - name: Login hub.docker.com
      run: docker login -u alexgavr89 -p ${{ secrets.DOCKER_HUB }}
      
    - name: Push the Docker image
      run: docker push alexgavr89/test_deploy:v${VERSION}
