name: Deploy app

on:
  push:
    branches:
      - task_2_good_test
  
  workflow_dispatch:

jobs: 
  docker_build:
      
    runs-on: ubuntu-latest

    steps:     
    - name: VERSION
      run: echo "${GITHUB_RUN_ID}"
      
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.4.1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t alexgavr89/test_deploy:${GITHUB_RUN_ID}
      
    - name: Login hub.docker.com
      run: docker login -u alexgavr89 -p ${{ secrets.DOCKER_HUB }}
      
    - name: Push the Docker image
      run: docker push alexgavr89/test_deploy:${GITHUB_RUN_ID}
