name: Deploy app

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t alexgavr89/test_deploy:$(date +%s)
