name: Deploy app

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        run: 'Test merge GOOD'
