
name: Test ssh

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs: 
  deploy:
      runs-on: ubuntu-latest

      steps:
      - name: SSH Setup
        uses: MrSquaare/ssh-setup-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST_TEST }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY_TEST }}
          private-key-name: id_rsa
          
      - name: Test ssh
        run: ${{ secrets.SSH_TEST_CONNECT }} 'ls /web/'
        
        
