
name: Test ssh

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs: 
  deploy:
      runs-on: ubuntu-latest

      steps:        
      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_TEST }}
          ssh-host: ${{ secrets.SSH_HOST_TEST }}
          ssh-port: ${{ secrets.SSH_PORT_TEST }}
          
      - name: Test ssh
        run: ${{ secrets.SSH_TEST_CONNECT }} 'ls /web/'
        
        
