
name: Test ssh

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs: 
  deploy:
      runs-on: ubuntu-latest

      steps:
#       - name: ssh deploy
#         # You may pin to the exact commit or the version.
#         # uses: easingthemes/ssh-deploy@c711f2c3391cac2876bf4c833590077f02e4bcb8
#         uses: easingthemes/ssh-deploy@v2.2.11
#         with:
#           # Private Key
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_TEST }}
#           REMOTE_HOST: ${{ secrets.SSH_HOST_TEST }}
#           REMOTE_USER: ${{ secrets.SSH_NAME_TEST }}
#           REMOTE_PORT: ${{ secrets.SSH_PORT_TEST }}

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_TEST }}
          username: ${{ secrets.SSH_NAME_TEST }}
          key: ${{ secrets.SSH_PRIVATE_KEY_TEST }}
          port: ${{ secrets.SSH_PORT_TEST }}
          script: whoami
          
        
